dataset: MNIST
n_noise_features: 100
epochs: 40
k: 1
gen_steps: 1
discriminator_filters: 128
generator_filters: 128
batch_size: 128
print_every: 1
checkpoints: 5
rolling_window: 100
discriminator_label_noise: False
discriminator_input_noise: False