dataset: CELEBA
n_noise_features: 100
epochs: 20
disc_steps: 5
gen_steps: 1
lambda_pen: 10
discriminator_filters: 64
generator_filters: 64
batch_size: 64
print_every: 1
checkpoints: 1
rolling_window: 100
discriminator_label_noise: False
discriminator_input_noise: False
resume_training: None